### ISSUE TITLE
[7.0b10] matériel

### ISSUE THREAD

**Issue by Cissoubaka** [cedrick-f/pySequence#1]
A l'ouverture d'une séquence parfois, la liste des matériels n'est pas bonne.

Les noms sont remplacés par "nouveau matériel", bien que sur la fiche le nom soit le bon.

**Comment by cedrick-f** [comment]
Bonjour
Merci pour cette info, mais si vous pouviez joindre la procédure précise pour reproduire le bug (et éventuellement un fichier .seq), je gagnerais du temps...
CF

**Comment by Cissoubaka** [comment]
[sequence.zip](https://github.com/cedrick-f/pySequence/files/501486/sequence.zip)

Voici les fichiers,
pour la procédure : j'ai crée les 2 sequences et la progression, ensuite j'ai fermé pysequence pour le réouvrir un peu plus tard, et la, le matériel était remplacé par "nouveau matériel".
J'ai fermé les séquences, les ai réouvert et la plus de problème

**Comment by Cissoubaka** [comment]
J'ai un peu regarder de plus près comment reproduire le problème:
il faut ouvrir d'abord la progression, puis ensuite les séquences.

**Comment by cedrick-f** [comment]
Merci, je vais corriger ça dans la semaine ...
