### ISSUE TITLE
Lecteur PDF intégré

### ISSUE THREAD

**Issue by SebCanet** [cedrick-f/pySequence#10]
Bonjour,
ce qui serait super intéressant serait de pouvoir intégrer un lecteur PDF, pour ne pas avoir besoin de ce satané Adobe Reader !

Merci !

**Comment by cedrick-f** [comment]
Ça sera possible après le passage à wxpython phoenix ... pour l'instant, le lecteur PDF ne fonctionne pas correctement.

**Comment by cedrick-f** [comment]
Problème résolu à partir de la version 8

**Comment by SebCanet** [comment]
Super ! Merci.
