### ISSUE TITLE
Empaqueter

### ISSUE THREAD

**Issue by SebCanet** [cedrick-f/pySequence#12]
Bonjour,
dans 'Fichier', ce qui serait intéressant serait de pouvoir générer un zip qui contient tout le projet avec aspiration des fichiers liés, un paquet complet avec toutes les pièces jointes.

Merci !

**Comment by cedrick-f** [comment]
Bonjour
En voila une idée qu'elle est bonne !
Je rajoute à ma TODO list !

**Comment by cedrick-f** [comment]
Bonjour
Ce sera dans la 7.1.beta-9 !
