### ISSUE TITLE
Liste Profs non complète

### ISSUE THREAD

**Issue by af1964** [cedrick-f/pySequence#13]
Dans une séquence, j'ai créé deux enseignants. L'un est enregistré et on le retrouve dans la liste (charger). L'autre n'apparait pas.
PySequence 7.1 Beta 8

**Comment by cedrick-f** [comment]
Bonjour
Merci pour m'avoir signalé ce bug.
Il est corrigé.
Reste à attendre un peu la release v7.1.beta-9 ...
