### ISSUE TITLE
Fichier provoquant une erreur à l'enregistrement

### ISSUE THREAD

**Issue by af1964** [cedrick-f/pySequence#14]
PySéquence 7.1 Beta 8
![capture 1](https://user-images.githubusercontent.com/22676137/30247133-e14a8086-960c-11e7-89ab-1c36657d3287.PNG)
![capture2](https://user-images.githubusercontent.com/22676137/30247138-047216d2-960d-11e7-90ba-9db2c732fcf7.PNG)

**Comment by cedrick-f** [comment]
Bonjour
Serait-il possible d'avoir une méthode pour reproduire ce bug ? Les Traceback ne me suffisent pas ...
Merci

**Comment by cedrick-f** [comment]
Voir #18
