### ISSUE TITLE
Fichier ne voulant plus se charger

### ISSUE THREAD

**Issue by af1964** [cedrick-f/pySequence#15]
[Sequence Energie.zip](https://github.com/cedrick-f/pySequence/files/1290346/Sequence.Energie.zip)

![capture3](https://user-images.githubusercontent.com/22676137/30247183-68343b40-960e-11e7-8c84-2db9cb99c3b4.PNG)

**Comment by cedrick-f** [comment]
Bonjour
Je crois avoir débusqué (et corrigé) ce bug.
Voici un fichier qui devrait s'ouvrir avec la version 7.1.beta-8 :
[Sequence Energie CORR.zip](https://github.com/cedrick-f/pySequence/files/1290405/Sequence.Energie.CORR.zip)
Merci de me signaler si c'est bien le cas ...

**Comment by Mikeinty** [comment]
Bonjour, je confirme le fichier s'ouvre avec pySequence 7.1.16.

Par contre, les exemples en fichier 
EE_abrisdebus.prj
ITEC_eco-passerelle.prj
Projet_site_isole.prj

ne s'ouvrent pas fichiers corrompus

**Comment by cedrick-f** [comment]
Versions de fichiers obsolètes
