### ISSUE TITLE
Autre fichier ne voulant plus s'ouvrir

### ISSUE THREAD

**Issue by af1964** [cedrick-f/pySequence#16]
[EESEQ00Introcuction.zip](https://github.com/cedrick-f/pySequence/files/1290351/EESEQ00Introcuction.zip)
![capture4](https://user-images.githubusercontent.com/22676137/30247209-2601e37a-960f-11e7-9566-87958d6f86c3.PNG)

**Comment by cedrick-f** [comment]
Bonjour
Ce fichier ne s'ouvre pas car une erreur s'est produite à son enregistrement... sans doute en rapport avec le ticket #14 ...
