### ISSUE TITLE
Compétences ETT et EE

### ISSUE THREAD

**Issue by af1964** [cedrick-f/pySequence#17]
PySequence 7.1 Beta 8
Compétences ETT intègrent O6 et O8 (ne doivent pas)
Compétences EE vident.

**Comment by cedrick-f** [comment]
Bonjour

> Compétences ETT intègrent O6 et O8 (ne doivent pas)

Pourquoi ? Elles seraient seulement évaluées en projet ?

> Compétences EE vident.

Problème réglé dans v7.1.beta-9 ... publication imminente ...

**Comment by patrickgmail** [comment]
Bonsoir, Projet EE 
CO7.EE3 et CO7.ee4 n'apparaissent pas pour les affecter aux tâches de projets.

**Comment by cedrick-f** [comment]
Bonjour
Je viens de corriger ça.
Sera effectif dans v7.1.12.
