### ISSUE TITLE
Séance créée non accessible

### ISSUE THREAD

**Issue by af1964** [cedrick-f/pySequence#18]
J'ai crée un séance avec un lien sur un répertoire dont le nom était de la forme "0.xxxxx".
Le logiciel n'y pas accédé (pas visible à l'écran).
Je suis sorti de PySéquence. J'ai modifié le nom du répertoire. Lorsque que je veux accéder à la séance, elle n'apparait pas (voir les fichiers)
![capture5](https://user-images.githubusercontent.com/22676137/30247966-914896a0-961f-11e7-8b5e-2315f4006da2.PNG)
![capture6](https://user-images.githubusercontent.com/22676137/30247968-97137514-961f-11e7-9ea5-1ef6c45c0a69.PNG)
[SEQ_00.zip](https://github.com/cedrick-f/pySequence/files/1290423/SEQ_00.zip)

**Comment by cedrick-f** [comment]
Bonjour
Je n'arrive pas à reproduire ce bug, le fichier SEQ_00.seq s'ouvre parfaitement chez moi.
Effet v7.1.beta-9 ? effet poste de travail ?

Est-ce que je peux voir les 10 premières lignes qui s'affichent dans la console ?
(merci de répondre dans ce fil)

**Comment by af1964** [comment]
Le fichier s'ouvre. Là n'est pas le problème. Si vous pointez sur la séance, elle n'est pas accessible en modification.
![capture9](https://user-images.githubusercontent.com/22676137/30248441-3f4d08b4-9628-11e7-8b93-340d8a35608b.PNG)

**Comment by af1964** [comment]
Désolé..., je ne connais pas encore tous les modes du Github

**Comment by cedrick-f** [comment]
J'ai eu du mal, mais je crois que c'est résolu (v7.1.beta-9)
A vérifier ...

**Comment by cedrick-f** [comment]
Pas de réponse : je suppose que le problème est réglé.
