### ISSUE TITLE
Copier Coller : Liste ne fonctionne plus entre version 6 et 7

### ISSUE THREAD

**Issue by af1964** [cedrick-f/pySequence#2]
Version 7 - Beta 11 
Erreur lors d'un copier coller dans la fenêtre de  structure

File "C:\...." line 1822, in CollerElem
AttributeError : Sequence instance has no attribute 'panelParent'

**Comment by cedrick-f** [comment]
Merci pour ce retour, ce sera corrigé très prochainement.
