### ISSUE TITLE
Nom d'établissement

### ISSUE THREAD

**Issue by af1964** [cedrick-f/pySequence#21]
Le nom de mon établissement a changé.
Lycée Germaine Tillion à Montbéliard (fusion de Viette et Grand Chénois.
J'ai essayé votre fonction de recherche d'établissement. Le programme fait sa recherche et il ne s'arrête pas comme le montre l'image.
![capture10](https://user-images.githubusercontent.com/22676137/30248605-244add9a-962b-11e7-96bf-d4a339b1b9cf.PNG)

**Comment by cedrick-f** [comment]
Le problème à été résolu, et le fichier Etablissements.xml mis à jour (v7.1.beta-9)
