### ISSUE TITLE
pySequence 7.1.10 erreur au lancement

### ISSUE THREAD

**Issue by E-Selim** [cedrick-f/pySequence#22]
Bonjour,
J'ai ce message d'erreur au lancement.

![erreur_pysequence](https://user-images.githubusercontent.com/22724428/30800083-257a92d6-a1df-11e7-9d68-b6df19cdb488.PNG)

Peut-être qu'il me manque quelque chose... Ou que j'ai raté une config...
Système : Win7 Pro 64b
Merci d'avance,
Selim

**Comment by cedrick-f** [comment]
Bonjour
Cela devrait aller mieux avec la [version v7.1.11 ](https://github.com/cedrick-f/pySequence/releases/tag/v7.1.11)
CF
