### ISSUE TITLE
La case Support est pré-remplie

### ISSUE THREAD

**Issue by E-Selim** [cedrick-f/pySequence#23]
![pseq-support](https://user-images.githubusercontent.com/22724428/30852556-7383e5a4-a2ac-11e7-85d8-2f8b9c5230ef.PNG)

Lors de la création d'un nouveau projet, la case "Support" de la fiche contient "Support". Les autres cases, non renseignées restent, elles, vides.
Si on ajoute quelque chose dans la case la valeur se modifie. Est-ce voulu?
pySequence 7.1.11 Win7Pro-64

Selim

**Comment by cedrick-f** [comment]
Bonjour
C'est forcément un truc voulu ... mais je ne me rappelle pas pourquoi j'ai fait ça.
Je peux l'enlever.

**Comment by E-Selim** [comment]
Bonjour,
Je ne saurais dire, si je préfère l'enlever ou pas.
Pour l'instant, disons que comme je ne sais pas quoi mettre dedans, ça attire le regard.

**Comment by cedrick-f** [comment]
Et si c'était pour cette raison que j'ai fait ça ... va savoir ...
