### ISSUE TITLE
Liste des profs non sauvée

### ISSUE THREAD

**Issue by E-Selim** [cedrick-f/pySequence#24]
Sur un projet où j'enregistre les profs avec le bouton sauvegarder, je ne peux pas les réimporter.
Même dans le projet lui-même.

![prof-vide](https://user-images.githubusercontent.com/22724428/30854165-32b6e0bc-a2b1-11e7-8256-6638b879574e.PNG)

pySequence 7.1.11 - Win7Pro x64

Selim

**Comment by cedrick-f** [comment]
Bonjour
Je n'arrive pas à reproduire ce bug.
Essaye de supprimer (ou renommer) le fichier src/profs.xml et relance pySéquence.

**Comment by E-Selim** [comment]
Bonjour,

Je n'arrive pas à localiser de répertoire src ni de fichier profs.xml (recherché sur tout le disque).
C'est un répertoire de travail qui devrait exister?

**Comment by cedrick-f** [comment]
Au temps pour moi : prof.xml doit s'enregistrer dans le dossier /bin de pySéquence.
S'il ne s'y trouve pas après une opération de sauvegarde, c'est qu'il y a un problème d'enregistrement.
Y a-t-il un message de succès après l’enregistrement ?

**Comment by E-Selim** [comment]
J'ai pensé que ce devait être un problème de droits d'écriture et j'ai été tester sur plusieurs ordinateurs différents. Vu que je n'avais pas le message de succès dont tu parles et que je me rappelais l'avoir déjà vu...
C'était bien ça!
Donc ce n'est pas un bug mais une config étonnante de mon PC du lycée.
Merci pour ton aide!
Et merci aussi pour ce programme qui nous aide bien au quotidien. Plus je comprends comment l'utiliser plus je le trouve génial :)
