### ISSUE TITLE
Faux positif par Avast

### ISSUE THREAD

**Issue by cedrick-f** [cedrick-f/pySequence#25]
Depuis la version 7.1.10 l'antivirus Avast détecte pysequence.exe comme un virus : il s'agit d'un faux positif !
Pour remédier au problème : 

1. Accéder à la zone de quarantaine d'Avast
2. Faire un clic-droit sur Sequence.exe 
3. Faire Restaurer et ajouter aux exclusions

**Comment by E-Selim** [comment]
Oui j'ai eu le cas et j'ai aussi utilisé leur formulaire pour signaler un faux-positif.
En espérant qu'ils le prennent rapidement en compte.

**Comment by cedrick-f** [comment]
D'après Avast, Sequence.exe vient d'être whitelisté.
A vérifier ...

**Comment by E-Selim** [comment]
Il semblerait qu'Avast recommence...
Faux positif sur /bin/Sequence.exe
Désolé!
