### ISSUE TITLE
Association des extensions de fichier

### ISSUE THREAD

**Issue by E-Selim** [cedrick-f/pySequence#26]
Bonjour,
Je me rappelle qu'il y avait un moyen d'associer les extension qu'utilise pySequence avec le programme.
C'était dans src/register.py je crois.
Je ne trouve plus comment le faire automatiquement, sans aller moi même trifouiller le registre.

J'ai raté quelque chose?

Merci d'avance,

Selim

**Comment by cedrick-f** [comment]
Bonjour
Pour une raison que j'ai oubliée (encore !), j'ai désactivé cette fonctionnalité pour les versions portables de pySéquence.
Je vais faire une version installable ...
