### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by patrickgmail** [cedrick-f/pySequence#29]
Bonsoir
Pourrait-il y avoir un auto-save (avec fichier .bak). Le bug d'enregistrement des RTF, quand j'ai voulu généré le dossier ZIP complet m'a planté toute l'application et j'ai perdu les 2 dernières heures de boulot.

**Comment by cedrick-f** [comment]
Bonjour
Je mets ça dans la TODO list

**Comment by cedrick-f** [comment]
Fait (à partir de 8.0-beta.23)
