### ISSUE TITLE
Tutoriel

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#3]
Bonjour,
J'avais découvert pysequence à ses débuts et il a bien changé. Existe-t-il un tutoriel relativement à jour, pour apprendre à s'en servir? Car le lien: https://github.com/cedrick-f/pySequence/wiki/Tutoriels renvoie à des pages textes. Notamment par où commencer. Nouvelle séquence ou nouvelle progression?
Je me pose également les questions suivantes:
Nombre d'élève = nb d'élève de la classe entière
Nombre de groupe à effectif réduit = nb de groupe de tp de la classe sitée au-dessus
Nombre de groupe Etude de projet = nb de projet en ssi terminale ou sti2d terminale en projet
Nombre de groupe Activités pratiques = je ne comprends pas, où est la différence avec Nombre de groupe à effectif réduit?
J'utilise la version 7.0-beta.11
En vous remerciant pour votre aide

**Comment by cedrick-f** [comment]
Bonjour
Il n'y a pas de tutoriels car je manque de temps pour en faire ... et pour être honnête, j'aimerais bien recruter de l'aide parmi les utilisateurs :)

La partie progression est en travaux, mais doit être suffisamment fonctionnelle. En principe, il faut commencer par là : 
1) Progression : on crée, depuis la Progression, une succession de séquences, sur toute la durée de la formation, et on fixe les diverses compétences à aborder en cliquant directement sur la fiche. L'objectif étant de construire une Progression cohérente (prérequis/objectifs), sans rien oublier.
2) Séquences : une fois les Séquences créées, il faut les détailler : Séances ...
Mais rien n'empêche de procéder à l'envers ...

Les groupes à effectif réduit sont ce qu'on appelle les groupes de classe : en général, il y en a 2 par classe.
Les groupes Activités pratiques sont des sous-groupes des groupes à effectif réduits. Ce peut être le nombre de groupes d'élèves que l'on met en rotation de TP.
Je ne sais pas si je suis très clair ...

Bon courage !

**Comment by michelwend** [comment]
Merci pour votre message. Je veux bien faire un tuto sous writer pour l'instant sur la partie séquences...

**Comment by cedrick-f** [comment]
Merci d'avance pour cette initiative, beaucoup d'utilisateurs apprécieraient !
Peut-être devriez-vous utiliser la dernière version : [7.1-beta.1](https://github.com/cedrick-f/pySequence/releases/tag/v7.1-beta.1) ...

**Comment by michelwend** [comment]
Bonsoir,
Je viens de télécharger la nouvelle version, la fenêtre dos se lance ainsi que la nouvelle figure de démarrage. Mais tout se ferme sans que je puisse avoir accès au programme en lui-même. J'avais déjà eu cet effet avec des versions antérieures et le fait de passer à une version supérieure m'avait permis de m'en sortir. Mais là comme j'ai la dernière version je ne sais pas comment faire. J'ai mis le programme dans: C:\Program Files (x86)\pySequence. J'utilise windows 10-64. Pouvez-vous m'aider en vous remerciant.

**Comment by cedrick-f** [comment]
J'ai corrigé ... même version ... même lien

**Comment by michelwend** [comment]
Merci cela fonctionne, à bientôt

**Comment by SebCanet** [comment]
Bonjour,
je me permets de relancer ce post car pas mal de liens ont sauté dans le wiki apparemment, les fichiers png ne s'affichent pas: [https://github.com/cedrick-f/pySequence/wiki/Presentation](https://github.com/cedrick-f/pySequence/wiki/Presentation)

Merci, et je comprends fort bien le pb de lancer les contributeurs à bosser sur la doc...

**Comment by cedrick-f** [comment]
Bonjour
La doc de pySéquence est censée se trouver sur le site web : [http://cedrick-f.github.io/pySequence](http://cedrick-f.github.io/pySequence)... mais on ne peut pas dire qu'il soit à jour non plus !
Si tu connais un peu Github, l'édition HTML, et pySéquence, je peux t'inviter à collaborer à la doc.
Tu peux te faire un idée de comment est construit le site en clonant la branche gh-pages...

**Comment by SebCanet** [comment]
Je suis le développeur de Blockly@rduino ([https://github.com/technologiescollege/Blockly-at-rduino](https://github.com/technologiescollege/Blockly-at-rduino)), et je peine à entretenir un site, je n'ai aucune doc et je galère à gérer un wiki, heureusement du monde se répond sur mon forum...donc les pb de doc je connais bien :-D

**Comment by nada1312** [comment]
Bonjour
J'ai commencé à utiliser le nouveau pySequence 11 mais je n'arrive pas à réduire l'effectif. il y a que l'option effectif complet ???
Merci de m'aider

**Comment by nada1312** [comment]
merci
avant je pouvais choisir le nombre d'élève au lieu de 32 mais maintenant avec cette nouvelle version je ne peux plus

**Comment by nada1312** [comment]
avant on avait l'option effectif ou je pouvais choisir 4 élèves ou 2 élèves ou effectif réduit 16 élèves 
Mais maintenant il y a 32 par defaut

**Comment by cedrick-f** [comment]
Quel enseignement, et quel type d'activité ?

**Comment by nada1312** [comment]
sti2d sin et toutes les activités
