### ISSUE TITLE
Projet commun à 2 SPé. STI2D

### ISSUE THREAD

**Issue by E-Selim** [cedrick-f/pySequence#30]
Bonjour,
Je ne sais pas si ma démarche est correcte. Et si j'utilise l'outil comme il faut.

J'ai un groupe d'élèves (2 AC et 1 EE) qui font leur projet ensemble.
J'ai crée 2 fiches projet. L'une contient l'élève EE (ee) et le groupe AC et l'autre le détail des 2 élèves AC (ac1 et ac2) et le groupe EE (1 seul élève).
Sur une des taches ont participé ee et ac1 mais pas ac2. Du coup j'ai du mal à remplir les fiches...
Si quelqu'un voit comment faire, je suis preneur.

Et en question subsidiaire, y aurait-il moyen de lier la fiche des AC et le groupe AC de la fiche EE. De manière à remplir chaque tache dans une seule fiche et voir l'avancement se compléter sur l'autre?

Merci de vos réponses,

**Comment by cedrick-f** [comment]
Réforme du bac STI2D : le sujet devient obsolète.
