### ISSUE TITLE
Pb association de fichiers

### ISSUE THREAD

**Issue by E-Selim** [cedrick-f/pySequence#31]
Bonjour,
Dans la version installable, on a une erreur si on essaye de double-cliquer sur un fichier de pySequence (.prj .seq etc.) alors que pySéquence est déjà ouvert avec un autre fichier.

![dejalance](https://user-images.githubusercontent.com/22724428/32779846-82ef8af2-c93f-11e7-9195-c90f18898ec4.PNG)

Et lorsqu'on clique sur OK

![dejalance-2](https://user-images.githubusercontent.com/22724428/32779865-92364424-c93f-11e7-9ec0-831425859605.PNG)

Merci d'avance,

**Comment by cedrick-f** [comment]
Bonjour
Merci pour ce signalement. C'est corrigé ... pour la prochaine version !

**Comment by E-Selim** [comment]
Avec plaisir, plus j'apprends comment l'utiliser plus je l'apprécie!

Et merci pour ta réactivité et ton professionnalisme.
