### ISSUE TITLE
Grilles de projet non générées

### ISSUE THREAD

**Issue by dukenux** [cedrick-f/pySequence#34]
Bonjour,

Lorsque je tente de générer des grilles de projet (CTRL + G), j'ai une fenêtre qui me dit que les grilles ont été générées avec succès dans le dossier que j'avais sélectionné, mais lorsque je vai dans ce dossier, il est vide! Rien n'a été généré.

J'ai testé avec PySequence 6.2, puis PySequence 7.1.16, résultats identiques. Rien n'est généré.
J'ai testé également sous Win7 et Win10. Idem, rien n'est généré.
(Les compétences pour chaque tache sont pourtant bien remplies).

Avez-vous une idée de ce que j'aurais oublié de faire?

**Comment by cedrick-f** [comment]
Bonjour
Ce problème se produit quand l'ordinateur n'est pas équipé de MS Excel.
