### ISSUE TITLE
Impossible de lancer la Beta 8.23

### ISSUE THREAD

**Issue by Belgarath37** [cedrick-f/pySequence#35]
Bonjour,

Impossible de lancer la version Beta 8.23 . j'ai systematiquement l'erreur ci dessous et rien d'autre ne s'affiche.

![pysequence_bug](https://user-images.githubusercontent.com/41510277/51836471-cdb9f880-2300-11e9-82eb-e8b0d77c1060.jpg)

Merci.

**Comment by cedrick-f** [comment]
Bonjour
Le problème devrait être réglé...

**Comment by Belgarath37** [comment]
En effet, Merci beaucoup.
