### ISSUE TITLE
compilation des sources

### ISSUE THREAD

**Issue by Belgarath37** [cedrick-f/pySequence#36]
Bonjour, 

cela fait plusieurs version que j'ai envie de  me mettre dans les sources pour essayer de corriger quelques petits bug et éventuellement aider au dev. 
j'ai installé pyCham de jetbrains,  les sources mais
j'ai un gros problème, l'installation de la librairie cairo  j'ai fait l'install 2 fois en re-suivant pas a pas les instructions mais rien n'y fait ... les fichiers utilisant cairo ne compilent pas impossible de détecter la librairie... 

Auriez vous une solution plus simple pour l'installer ? un moyen de contourner le problème ?
Merci.

**Comment by cedrick-f** [comment]
Bonjour
Je ne sais pas quelle méthode tu as suivie, mais la bonne, c'est [celle là](https://github.com/cedrick-f/pySequence/blob/master/Installation_Windows_py3.md).
En principe, il est inutile de compiler quoi que ce soit... 

Cédrick

**Comment by Belgarath37** [comment]
Merci pour l'info.  je vais essayer .
En fait j’étais parti avec les infos de la page des prérequis :LangageEtDependances  qui indique plutôt d'installer python 2.7 alors que celle que vous donnez dans le message ci dessus préconise python 3.6 .
Du coup je suis un peu perdu mais j'essaye la nouvelle méthode et je reviens vers vous .

**Comment by Belgarath37** [comment]
J'ai suivi la procédure et malheureusement 
👍 Dossier USER pour les données : D:\Travail_PROF\programmes\pySequence_SRC\src8.0-beta.27
Traceback (most recent call last):
  File "D:/Travail_PROF/programmes/pySequence_SRC/src/pysequence.py", line 69, in <module>
    import draw_cairo_seq, draw_cairo_prj, draw_cairo_prg, draw_cairo
  File "D:\Travail_PROF\programmes\pySequence_SRC\src\draw_cairo_seq.py", line 35, in <module>
    from draw_cairo import *
  File "D:\Travail_PROF\programmes\pySequence_SRC\src\draw_cairo.py", line 46, in <module>
    import cairo
ModuleNotFoundError: No module named 'cairo'
Process finished with exit code 1

**Comment by cedrick-f** [comment]
Bonjour
Peux tu faire un `pip freeze` pour qu'on voit les éventuels problèmes de modules ?

**Comment by Belgarath37** [comment]
C'est bien ça !!
cette fois j'arrive a le lancer ...

Merci beaucoup. Je vais me plonger plus avant dans le code.
Encore merci pour votre aide 
pour info si ça peu aider d'aut'e utilisateurs mon pip freeze :
C:\windows\system32>pip freeze
beautifulsoup4==4.7.1
cairocffi==0.9.0
cffi==1.11.5
comtypes==1.1.7
html5lib==1.0.1
Jinja2==2.10
Markdown==3.0.1
MarkupSafe==1.1.0
Pillow==5.4.1
pycparser==2.19
pyenchant==2.0.0
PyMuPDF==1.14.8
PyPDF2==1.26.0
pyperclip==1.7.0
pywin32==224
reportlab==3.5.13
six==1.12.0
soupsieve==1.7.3
webencodings==0.5.1
wxPython==4.0.4
xhtml2pdf==0.2.3
xlrd==1.2.0
xlwt==1.3.0

**Comment by cedrick-f** [comment]
> Je vais me plonger plus avant dans le code
Bonne plongée :)
