### ISSUE TITLE
Plantage à l'enregistrement des détails de la séquence pysequence V8.1.5

### ISSUE THREAD

**Issue by pburlando** [cedrick-f/pySequence#37]
Bonjour,

Pysequence plante à l'enregistrement des détails de la séquence.
Fichier -> Exporter les détails (ctrl+D)
Dans la nouvelle fenêtre éditeur de texte Fichier -> Enregistrer provoque Pysequence 8 a rencontré une erreur et doit fermer.
W7 pro sp1 64bits

[Seq4_objets_connectes_spe_1SI_V2.zip](https://github.com/cedrick-f/pySequence/files/3099888/Seq4_objets_connectes_spe_1SI_V2.zip)

Cordialement

**Comment by pburlando** [comment]
Pour préciser, la copie d'écran de l'erreur :
![plantagePysequence](https://user-images.githubusercontent.com/45093800/56455019-bd427880-6359-11e9-918c-01b859d36d48.jpg)

**Comment by cedrick-f** [comment]
Bug corrigé, Merci !
