### ISSUE TITLE
Produit et matériel

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#38]
On ne peut pas sauvegarder un produit ou un matériel en passant par classe. Il faut passer par produit et matériel dans l’arbre.

**Comment by cedrick-f** [comment]
Bonjour
Je n'arrive pas à produire un dysfonctionnement sur les systèmes ... pouvez-vous préciser ?

**Comment by michelwend** [comment]
Bonjour,
Je joint une capture d'écran
![2019-04-20 18_53_22-Produit et matériel · Issue #38 · cedrick-f_pySequence](https://user-images.githubusercontent.com/11646494/56460110-a6be1080-639d-11e9-97ba-ad4700640c9d.png)

**Comment by michelwend** [comment]
> 
> 
> Bonjour,
> Je joins une capture d'écran
> ![2019-04-20 18_53_22-Produit et matériel · Issue #38 · cedrick-f_pySequence](https://user-images.githubusercontent.com/11646494/56460110-a6be1080-639d-11e9-97ba-ad4700640c9d.png)
> Ici il est impossible d'ajouter un matériel

**Comment by cedrick-f** [comment]
A ce stade de la création d'un système, il faut modifier le nom dans le champ "Nom du..." (à droite).
Je sais : ce n'est pas très intuitif ...
