### ISSUE TITLE
Activité pratique et groupe

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#40]
Pour les activités pratiques ont peut seulement choisir la classe entière plus de possibilité de choisir des groupes

**Comment by michelwend** [comment]
Pour les activités pratiques ont peut seulement choisir la classe entière plus de possibilité de choisir des groupes

**Comment by cedrick-f** [comment]
C'est un bug ! Je m'y colle !

**Comment by cedrick-f** [comment]
Corrigé !
