### ISSUE TITLE
Page principale dépassement

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#41]
Bonjour,
Lors du choix d'une activité pratique sa représentation graphique (rose foncé) dépasse du cadre vert de la séquence; Voir le fichier joint

![2019-04-20 18_25_53-pySéquence 8](https://user-images.githubusercontent.com/11646494/56459839-db2fcd80-6399-11e9-9d5f-49c1b6f8928c.png)

**Comment by cedrick-f** [comment]
Cela vient de l'effectif qui est trop élevé. On peut désormais  ( #b7ab678) le modifier.
