### ISSUE TITLE
Dédoublement affichage cours

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#42]
Bonjour,
Dans la fenêtre principale l'affichage est dédoublé pour le cours. Je joins la capture d'écran et le fichier de la séquence
![2019-04-20 19_11_09-pySéquence 8](https://user-images.githubusercontent.com/11646494/56460259-3b297280-63a0-11e9-800b-51915e020110.png)
[19-20_s_SEQ-2_5semaines2.zip](https://github.com/cedrick-f/pySequence/files/3100416/19-20_s_SEQ-2_5semaines2.zip)

**Comment by cedrick-f** [comment]
Dans cet exemple, il y a une activité vide (sans nom ni type), juste avant le cours C1, ce qui provoque cet affichage.
Ce n'est pas top, mais c'est le comportement normal....
