### ISSUE TITLE
Activité pratique et groupe

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#44]
[19-20_s_SEQ-2_5semaines3.zip](https://github.com/cedrick-f/pySequence/files/3101429/19-20_s_SEQ-2_5semaines3.zip)
Bonjour,
Pour l'activité projet on peut maintenant choisir une partition de la classe mais pas pour les activités pratiques.
![2019-04-21 18_53_39-pySéquence 8](https://user-images.githubusercontent.com/11646494/56473147-3ed3fc80-6467-11e9-9937-6e7cb4cfd9c0.png)

**Comment by cedrick-f** [comment]
C'est un bug dans le fichier Excel du référentiel SSI. J'ai corrigé, mais pour appliquer les modification avant la prochaine version, il faut :
- télécharger le nouveau fichier xls
- le placer dans le dossier /referentiels
- supprimer le fichier xml associé
- ouvrir les documents créés avec l'ancien référentiel en faisant Outils/Ouvrir et réparer

**Comment by michelwend** [comment]
Merci je vais attendre la prochaine version. A bientôt
