### ISSUE TITLE
Affichage et fermeture un ou deux écrans

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#45]
Bonjour,
Je travaille sur deux écrans en mode étendu chez moi. Lorsque je ferme l'application sur le deuxième écran tout se passe correctement. Si ensuite je ne travaille que sur le seul écran de mon portable l'ouverture se fait mais "part "sur le deuxième écran qui n'est plus branché donc l'application n'est plus accessible. J'espère que c'est à peu prêt clair? Merci encore et bonne journée

**Comment by cedrick-f** [comment]
C'est très clair, je regarde ça de plus près...
