### ISSUE TITLE
pySequence_8.1.8 se ferme

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#47]
Bonsoir,
Cette version se ferme au lancement. Le carré de pySequence apparaît puis se referme et je n'arrive donc pas à démarré le logiciel. J'ai installé cette version à partir du zip sous la racine:
C:\pySequence\
Auriez-vous une solution?

**Comment by cedrick-f** [comment]
En effet, une mise à jour de cairocffi qui ne se freeze plus correctement ...
Est-ce que ça va mieux avec la 8.1.9 ?

**Comment by michelwend** [comment]
Bonjour,
Je viens de faire l'essai, malheureusement le problème persiste.

**Comment by michelwend** [comment]
> Bonjour,
> Je viens de faire l'essai, malheureusement le problème persiste.
