### ISSUE TITLE
pySequence_8.1.9 se ferme

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#48]
Bonjour,
Je viens de faire l'essai avec la 8.1.9, malheureusement le problème persiste.
Le carré de pySequence apparaît puis se referme mais la persistance du carré à l'écran semble plus longue qu'avec la version 8.1.8.

**Comment by cedrick-f** [comment]
J'ai pas mal galéré, mais je crois que cette fois ci, c'est la bonne.

**Comment by michelwend** [comment]
Oui merci beaucoup! Résolu avec la 8.1.10
