### ISSUE TITLE
Erreur lors de l’insertion d'un prof dans une progression

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#49]
Bonjour,
J'ai voulu ajouter l'équipe pédagogique. L'insertion du prof1 se passe bien. Mais en le sélectionnant à nouveau pour préciser son nom pysequence se ferme. Je m'en sors en modifiant cela dans l'encadré inférieur.
A bientôt
[19-20_s_progression3.zip](https://github.com/cedrick-f/pySequence/files/3195046/19-20_s_progression3.zip)

pySéquence 8 a rencontré une erreur le 2019-05-19 13:03:55.515752
Version : 8.1.10

Description d'une méthode pour reproduire l'erreur :

=================TraceBack====================
File objects_wx.py, line 13830, in OnLeftDClick

File pysequence.py, line 1831, in AfficherLien

File pysequence.py, line 12723, in __eq__
==============================================

**Comment by cedrick-f** [comment]
Bonjour
Ceci ne devrait se produire qu'en faisant un double-clic ... mais un double clic à cet endroit ne devrait rien faire du tout.
Je corrige.

**Comment by cedrick-f** [comment]
Juste une question : il n'y avait que ça dans le rapport d'erreur ou bien c'est le copier/collé qui en a tronqué des bouts ?

**Comment by michelwend** [comment]
Voici le copier collé complet:

pySéquence 8 a rencontré une erreur le 2019-05-19 13:03:55.515752
Version : 8.1.10

Description d'une méthode pour reproduire l'erreur :




=================TraceBack====================
File objects_wx.py, line 13830, in OnLeftDClick

File pysequence.py, line 1831, in AfficherLien

File pysequence.py, line 12723, in __eq__
==============================================

**Comment by cedrick-f** [comment]
Ok, merci. J'ai aussi corrigé la fonction de génération de rapport ...
