### ISSUE TITLE
Première approche de pysequence

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#5]
Bonjour,
Je suis en train de m'imprégner du logiciel pysequence. Les remarques que je fais par la suite son surtout pour savoir si j'ai bien compris la démarche d'utilisation et non pour émettre une critique par rapport au travail réalisé. Pour moi l'avantage fondamental de pysequence est l'élaboration de fiches de présentation générique des séquences pour l'ensemble de nos enseignement en sciences de l'ingénieur.
Si j'ai bien compris le logiciel s'articule autour de la notion de séquence donc pour cela je vais utiliser ce lien:
https://www.ac-paris.fr/portail/jcms/p1_544963/progression-pedagogique-1re-sti2d
qui propose dans le fichier matrice et progression pédagogique première; notamment ces directives (page 5/43): Chaque séquence comprend de 2 à 4 semaines consécutives au maximum
Dans pysequence les fiches de séquences sont très encadrées et guidées. Ce qui est moins le cas pour les fiches de séances. Pour ma part j'utilise celle proposée par le site:
http://www.mysti2d.net/mysti2dter/ qui est proposée dans chaque début de tp que j'ai un peu remanié et qui est disponible ici pour la version itec: http://wendling.xyz/doc/index.php?f=1585beee382861 et que je mettrai donc en lien extrene comme le propose le logiciel.
C'est donc avec ces deux éléments que je vais mettre à plat ma progression pédagogique pour la sti2d en ETT et en ITEC cette année 2016-2017.
Pour utiliser au mieux les onglets de pysequence je vais déclarer une classe de 33 élèves en 1sti2d composée de deux groupes à effectif réduit 16 élèves en ITEC et 17 en SIN et 8 groupes en activités pratiques. Le classement proposé par pysequence est à mon avis peu pratique. Le plus simple serait de prévoir une feuille à part qui contiendrait les noms élèves avec différentes colonnes à cocher par séquence ou groupe de séquences pour connaître leur groupe ou classe suivant la date en important un fichier.csv par exemple. De plus il manque le document d'accompagnement dans l'onglet "Bulletins officiels" que j'appellerai à ce moment texte officiel.
Voilà pour l'instant ect-ce que j'ai bien compris la philosophie du logiciel en vous souhaitant de bonnes fêtes, cordialement.

**Comment by E-Selim** [comment]
Bonjour,
Je reprends ce fil ancien pour voir comment tu as terminé ton année dernière.
Peux-tu me/nous faire un retour sur l'usage que tu as eu de pySequence?

Et le lien de ton document sur wendling.xyz demande un login...

Au plaisir de te lire,
Merci d'avance,

Selim
