### ISSUE TITLE
Choix année scolaire

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#50]
Le choix des années scolaires est délicat. On ne peut choisir les années que sur un étalement de 3 ans alors qu'a mon
![2019-05-19 17_21_02-pySéquence 8](https://user-images.githubusercontent.com/11646494/57984323-f5250480-7a5a-11e9-9c50-706062484613.png)
 avis une année scolaire ce fait sur deux ans. Ici je souhaite mettre l'année 19-20. A moins que la stratégie soit autre?

**Comment by michelwend** [comment]
Ok la stratégie est visiblement autre. Pour les secondes le choix ce fait sur une année scolaire. C'est une logique par cycle de formation.

**Comment by cedrick-f** [comment]
C'est une spécificité du programme de Spé SI, qui est écrit pour 2 ans.
