### ISSUE TITLE
Changement favicon prof

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#51]
Bonjour,
J'essaye de changer le favicon d'un prof mais cela ferme le le logiciel. Quel est la taille ou le format recommandé?
pySéquence 8 a rencontré une erreur le 2019-05-19 17:45:01.735188
Version : 8.1.10

Description d'une méthode pour reproduire l'erreur :

=================TraceBack====================
File objects_wx.py, line 5498, in OnClickImage

File objects_wx.py, line 5512, in SetImage

File widgets.py, line 90, in du_
==============================================

**Comment by cedrick-f** [comment]
Merci, c'est corrigé
