### ISSUE TITLE
Activité pratique et Groupe en filière STI2D

### ISSUE THREAD

**Issue by alaspeyres** [cedrick-f/pySequence#55]
Bonjour, pour les filières STI2D, les activités pratiques se font forcement en classe entière, il est impossible de choisir autre chose sur le logiciel.

**Comment by cedrick-f** [comment]
Bonjour
J'ai corrigé les fichiers "ref" de STI2D, ils figureront dans la prochaine _release_, mais sont déjà récupérables sur le dépôt.
Merci
