### ISSUE TITLE
Intégration bts cpi

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#56]
Bonsoir,
Quelle serait la procédure pour commencer à intégrer le bts cpi dans pysequence? En vous remerciant pour votre aide.

**Comment by michelwend** [comment]
Je viens de trouver cela:
https://github.com/cedrick-f/pySequence/blob/master/referentiels/README.md
je vais essayer de le mettre en oeuvre

**Comment by jcfricou** [comment]
Bonjour,

Bonne idée d’integrer ce bts. Si vous le souhaitez, je vous propose une réunion à distance pour vous expliquer la procédure.

**Comment by michelwend** [comment]
Bonjour,
Avec plaisir car les liens ci-dessus que j'ai trouvé son un peu légers.

**Comment by cedrick-f** [comment]
Bonjour
Grâce à un courageux collègue de Dijon, le référentiel STS CPI est à présent intégré.
Toutes les propositions d'amélioration sont les bienvenues !
