### ISSUE TITLE
Calendrier Scolaire

### ISSUE THREAD

**Issue by davidzfr** [cedrick-f/pySequence#6]
Bonjour,

Tout d'abord merci pour votre travail. ;)

En Nouvelle-Calédonie, nous commençons l'année scolaire le 13 février et elle se terminer aux alentours du 20 décembre. Est-il possible de changer le calendrier scolaire dans pySequence?

D'avance merci pour votre réponse.

David Rouet
Nouveau Lycée du MONT-DORE
Nouvelle Calédonie
Bac Pro SN
BTS SN

**Comment by cedrick-f** [comment]
Bonjour, 
Je n'avais pas pensé à ça !
Je vais ajouter cette possibilité.
Merci pour ce retour.

CF
