### ISSUE TITLE
Secondes SNT 

### ISSUE THREAD

**Issue by lololh** [cedrick-f/pySequence#61]
Bonjour, j'ai récupéré la version 8..1.13 . J'essaie d'avancer sur le programme SNT. Je l'ai pris sur le depot car il n'est pas intégré directement dans cette version. Le sera-t-il dans les prochaines versions ?
J'ai essayé de modifier les lignes 20, 23 et 24 de l'onglet Séance pour permettre de sélectionner Effectif réduit et Demi-Groupe pour les activités de type Cours, Synthèse séquence et Evaluation.
En colonne F j'obtiens par exemple C G D en F20
Je supprime le fichier Ref_SNT.xml pour qu'il soit régénéré au redémarrage de Pysequence mais malgré cela je n'obtiens toujours que classe entière par exemple pour le cours... Est ce que j'ai loupé quelque chose ? 
Par ailleurs, pour être en conformité avec les nouveaux programmes il faudrait retirer l'appellation EE devant les enseignement CIT - SI - SNT en seconde.
Merci pour ce formidable outil.

Capture du fichier xml apparemment tenant compte des modifs faites : 
![image](https://user-images.githubusercontent.com/54577166/63761459-7c3b1180-c8c1-11e9-9eb2-d54add00947e.png)

**Comment by cedrick-f** [comment]
Bonjour

> il n'est pas intégré directement dans cette version. Le sera-t-il dans les prochaines versions ?
Oui, il le sera.

> il faudrait retirer l'appellation EE devant les enseignement CIT - SI - SNT en seconde.
C'est noté !

> J'ai essayé de modifier les lignes 20, 23 et 24 de l'onglet Séance pour permettre de sélectionner Effectif réduit et Demi-Groupe pour les activités de type Cours, Synthèse séquence et Evaluation.
En colonne F j'obtiens par exemple C G D en F20
Je supprime le fichier Ref_SNT.xml pour qu'il soit régénéré au redémarrage de Pysequence mais malgré cela je n'obtiens toujours que classe entière par exemple pour le cours... Est ce que j'ai loupé quelque chose ?

Et oui ! Ce n'est pas simple (et pas documenté), mais il faut aussi jouer sur l'arborescence des différents groupes, aux lignes 30 à 35.
J'ai modifié le fichier, ça devrait aller mieux.

**Comment by lololh** [comment]
merci pour la réactivité !
