### ISSUE TITLE
Problème copier coller

### ISSUE THREAD

**Issue by lololh** [cedrick-f/pySequence#62]
Lorsque je cherche à dupliquer une activité dans les séances, chaque copié collé se traduit par un message d'erreur et arrêt du logiciel
Exemple sur la capture suivante 
![image](https://user-images.githubusercontent.com/54577166/63762479-20718800-c8c3-11e9-82fe-ca2a5acda72a.png)

Merci

**Comment by cedrick-f** [comment]
Merci, j'ai corrigé ça ... (dispo dans la prochaine release)

**Comment by lololh** [comment]
Merci pour la réactivité !
