### ISSUE TITLE
referentiel SNT ?

### ISSUE THREAD

**Issue by Belgarath37** [cedrick-f/pySequence#64]
Bonjour, 

est il prévus d'ajouter le référentiel correspondant au SNT pour les secondes ? 
J'avoue avoir un peu regardé comment créer un référentiel mais cela me semble encore obscur ...

Merci.

**Comment by cedrick-f** [comment]
Le programme de SNT figurera dans la prochaine version, mais vous pouvez d'ors et déjà récupérer le fichier xls sur le dépôt et le mettre dans votre dossier pySquence/referentiels.
