### ISSUE TITLE
Affichage BO

### ISSUE THREAD

**Issue by E-Selim** [cedrick-f/pySequence#65]
Bonjour,
Les Bulletins officiels ne s'affichent pas dans leur onglet.
Lorsqu'on est sur l'item projet (en STI2D) dans l'arbre de gauche et qu'on clique sur l'onglet "Bulletins Officiels" rien ne s'affiche au dessous.
C'est peut-être parce qu'il nous en manque beaucoup des BO en STI2D :)

Version 8.3.1 mais ça le faisait aussi sur la 8.2. Je suis sous W7 pro.

Merci en tout cas pour le travail sur ce logiciel formidable !

**Comment by cedrick-f** [comment]
Bonjour
Les BO ne sont plus inclus dans avec pySéquence. En revanche, il est maintenant (v8.3.2) possible de les télécharger depuis pySéquence (ou manuellement).
