### ISSUE TITLE
[PROJET] Génération du PDF de validation 

### ISSUE THREAD

**Issue by Gouayave** [cedrick-f/pySequence#66]
![image](https://user-images.githubusercontent.com/2093475/73074268-846f9b00-3eb9-11ea-9d21-a43aac316301.png)
![image](https://user-images.githubusercontent.com/2093475/73074344-b41ea300-3eb9-11ea-8246-ed362c7b0141.png)
![image](https://user-images.githubusercontent.com/2093475/73074379-c7317300-3eb9-11ea-8de0-2e4caeb97827.png)

Lors de la génération de la fiche de validation si l'intitulé n'est pas complété, il y a un arret du logiciel.

**Comment by cedrick-f** [comment]
Ça se produit quand le fichier pdf est déjà ouvert (dans reader par exemple) et qu'on demande de le remplacer.
J'ai rajouté une protection contre la fermeture de pySéquence.
