### ISSUE TITLE
[PROJET] Arrêt lors du clique sur l’icône (?) 

### ISSUE THREAD

**Issue by Gouayave** [cedrick-f/pySequence#69]
![image](https://user-images.githubusercontent.com/2093475/73076544-9dc71600-3ebe-11ea-8eeb-118da1772457.png)
Lors du clique sur cette icône dans les propriétés générales du projet -> Arrêt.

![image](https://user-images.githubusercontent.com/2093475/73076708-ebdc1980-3ebe-11ea-88ea-be832c088b68.png)

**Comment by cedrick-f** [comment]
Merci, j'ai corrigé
