### ISSUE TITLE
Le code [[PB]] n'est pas pris en compte lors de la génération du fichier html -> pdf

### ISSUE THREAD

**Issue by Gouayave** [cedrick-f/pySequence#70]
Dans Ref_STI2D.xls, onglet Généralités_P1, il y le code PB
![image](https://user-images.githubusercontent.com/2093475/73076947-77ee4100-3ebf-11ea-8ec4-81d47f1d079c.png)

J'ai complété le champ :
![image](https://user-images.githubusercontent.com/2093475/73077117-d1567000-3ebf-11ea-9dc8-746080d7f925.png)

Lorsque je génère le pdf il n'y a pas la référence:
![image](https://user-images.githubusercontent.com/2093475/73077167-ef23d500-3ebf-11ea-85bb-0a7129f27583.png)

**Comment by cedrick-f** [comment]
En effet, c'est en fait le code PRE qui permet d'insérer cet attribut dans le PDF. J'ai rajouté en plus le code PB.
Il faudra sans doute virer les codes PRE dans les autres fichier html ...
