### ISSUE TITLE
[V8.3.5] Erreur lors du changement de la période

### ISSUE THREAD

**Issue by Gouayave** [cedrick-f/pySequence#72]
![Erreur_changement_periode](https://user-images.githubusercontent.com/2093475/76203902-af0e7c80-61f7-11ea-9f74-f83be4c91efd.gif)

Contexte: Création d'un projet STI2D 
Il n'y avait pas cette erreur dans la version 8.3.4

**Comment by cedrick-f** [comment]
Je n'arrive pas à le reproduire. 
Quel est le message d'erreur ?

**Comment by Gouayave** [comment]
Voilà, j'ai changé le référentiel, c'est peut être ça le pb.
Mais il marchait sur ma version précédente.
Je (re)test.

=================TraceBack====================
  File "objects_wx.py", line 6107, in onChanged

  File "objects_wx.py", line 6441, in MiseAJour

AttributeError: 'PanelPropriete_Projet' object has no attribute 'parctrl'
==============================================

**Comment by Gouayave** [comment]
My bad ! 
C'est une modif que j'ai faîte dans le fichier référentiel  STI2D.xls qui a créé ce bug. 
Je ferai une autre issue si nécessaire.
