### ISSUE TITLE
[V8.3.4] | Projet STI2D IT | Affichage des noms des onglets et fichier référentiel XLS

### ISSUE THREAD

**Issue by Gouayave** [cedrick-f/pySequence#73]
Lorsque l'on modifie le référentiel (Ref_STI2D.xls),
Le nom des onglets se mettent à jour uniquement si l'on ferme et (ré)ouvre le projet.
![image](https://user-images.githubusercontent.com/2093475/76221455-67005180-6219-11ea-936b-a7caa3400603.png)

**Comment by cedrick-f** [comment]
Résolu (à confirmer)
