### ISSUE TITLE
Premier essai 8.4-beta.10

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#75]
Bonjour,
Suite à l'installation de 8.4-beta.10, voici les messages d'erreur avec deux types de fichiers différents.
D'abord à l’ouverture de: 
C:\Program Files (x86)\pySequence\bin\Sequence.exe
La fenêtre de commande affiche:

> FILE_ENCODING utf-8
> SYSTEM_ENCODING utf-8
> pySequence installé dans C:\Program Files (x86)\pySequence\bin
> pySequence démarré dans C:\Program Files (x86)\pySequence\bin
> Dossier COMMUN pour les données : C:\ProgramData\pySequence
> Dossier USER pour les données : C:\Users\a\AppData\Roaming\pySequence
> sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
> Locale : 80 (FR: 80 ;EN: 58 )
> 8.4-beta.10
> ("Facteur d'echelle :", 1.0)
> Référentiels modifiés : []
> Version Adobe Reader None
> pdfviewer using PyMuPDF (GPL)
> .xlsx
> Options defaut
> Ouverture Options: C:\Users\a\AppData\Roaming\pySequence\sequence.cfg
> Recherche nouvelle version ...
>   proxies : {}
>    locale  : 8.4-beta.10
>    serveur : 8.3.5
>    serveur_beta : 8.4-beta.10

Puis lors de l'ouverture sous pysequece de 19-20_2_SEQ-1_6semaines.seq

> ouvrir D:\MECA\00_Progression\pysequence\2_snt\19-20_2_SEQ-1_6semaines.seq False D:\MECA\00_Progression\pysequence\2_snt
> ouvrir sequence D:\MECA\00_Progression\pysequence\2_snt\19-20_2_SEQ-1_6semaines.seq

Puis lors de l'ouverture sous pysequece de 19-20_2_progression.prg

> ouvrir D:\MECA\00_Progression\pysequence\2_snt\19-20_2_progression.prg False D:\MECA\00_Progression\pysequence\2_snt
> Ouverture progression D:\MECA\00_Progression\pysequence\2_snt\19-20_2_progression.prg

Enfin apparaît dans les fenêtres windows les messages suivants:

*Le fichier suivant est corrompu !!
D:\MECA\00_Progression\pysequence\2_snt\19-20_2_SEQ-1_6semaines.seq
Il est probablement tronqué suite à un echec d'enregistrement.
*Le fichier suivant est corrompu !!
D:\MECA\00_Progression\pysequence\2_snt\19-20_2_progression.prg
Il est probablement tronqué suite à un echec d'enregistrement.

Bien cordialement
mw

**Comment by cedrick-f** [comment]
Bonjour
Pourriez- vous m'envoyer les fichiers qui posent problème SVP ?
CF

**Comment by michelwend** [comment]
Bonjour,
Oui avec plaisir, merci encore

[2_snt.zip](https://github.com/cedrick-f/pySequence/files/4515571/2_snt.zip)

**Comment by cedrick-f** [comment]
Bonjour
La plupart des fichiers font 0 octets !
Ils ont été enregistrés quand ?

**Comment by michelwend** [comment]
Bonjour,
Désolé j'aurai dû faire cette vérification avant de faire un retour. Je vais les refaire, ils datent d'avril 2019 et c'est vrai qu'à cette époque je travaillais différemment. Je viens de tester avec mes fichiers de si plus récent et ils fonctionnent. Merci et encore désolé de mon erreur.
