### ISSUE TITLE
Création lien dans une scéance 8.4-14

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#78]
Bonjour,
En essayant de créer un lien dans une séance
![image](https://user-images.githubusercontent.com/11646494/80925988-8a1c2d00-8d94-11ea-9785-403d9fd8b65e.png)
J'ai les erreurs suivantes qui s'affichent:
`FILE_ENCODING utf-8
SYSTEM_ENCODING utf-8
pySequence installé dans C:\Program Files (x86)\pySequence\bin
pySequence démarré dans C:\Program Files (x86)\pySequence\bin
Dossier COMMUN pour les données : C:\ProgramData\pySequence
Dossier USER pour les données : C:\Users\a\AppData\Roaming\pySequence
sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
Locale : 79 (FR: 79 ;EN: 57 )
8.4-beta.14
Référentiels modifiés : []
Version Adobe Reader None
pdfviewer using PyMuPDF (GPL)
.xlsx
Options defaut
Ouverture Options: C:\Users\a\AppData\Roaming\pySequence\sequence.cfg
Recherche nouvelle version ...
  proxies : {}
   locale  : 8.4-beta.14
   serveur : 8.3.5
   serveur_beta : 8.4-beta.14
ouvrir D:\MECA\00_progression\pysequence\si\19-20-01_s1_SEQ_6sem01.seq False D:\MECA\00_progression\pysequence\si
ouvrir sequence D:\MECA\00_progression\pysequence\si\19-20-01_s1_SEQ_6sem01.seq
Différence
   labels
  xml: {'SEQINT': ['Intitulé de la Séquence', 'Intitulé de la Séquence pédagogique', <widgets.Grammaire object at 0x059214D0>], 'ELEVES': ['Élève(s)$m', 'Élèves', <widgets.Grammaire object at 0x05A27F10>], 'OBJEC': ['Objectif(s) de formation$m', 'Objectifs de formation', <widgets.Grammaire object at 0x05A27A70>], 'PRJVAL': ['Fiche(s) de validation de projet$f', 'Fiche de validation de projet', <widgets.Grammaire object at 0x05A27890>], 'EXIG': ['Fonction(s) de service$f', 'Fonctions de service', <widgets.Grammaire object at 0x05A270B0>]}
  xls: {'SEQINT': ['Intitulé de la Séquence', 'Intitulé de la Séquence pédagogique', <widgets.Grammaire object at 0x05A7DA30>], 'ELEVES': ['Élève(s)$m', 'Élèves', <widgets.Grammaire object at 
0x05A787F0>], 'OBJEC': ['Objectif(s) de formation$m', 'Objectifs de formation', <widgets.Grammaire object at 0x05A78850>]}
Traceback (most recent call last):
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 551, in CreerLien
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\lien.py", line 116, in DialogCreer
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\lien.py", line 399, in __init__
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_CENTRE_VERTICAL)" failed at ..\..\src\common\sizer.cpp(2077) in wxBoxSizer::DoInsert(): Vertical alignment flags are ignored in vertical sizers
Traceback (most recent call last):
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 551, in CreerLien
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\lien.py", line 116, in DialogCreer
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\lien.py", line 399, in __init__
wx._core.wxAssertionError: C++ assertion "!(flags & wxALIGN_CENTRE_VERTICAL)" failed at ..\..\src\common\sizer.cpp(2077) in wxBoxSizer::DoInsert(): Vertical alignment flags are ignored in vertical sizers`

Bien cordialement
[19-20-01_s1_SEQ_6sem01.zip](https://github.com/cedrick-f/pySequence/files/4571746/19-20-01_s1_SEQ_6sem01.zip)

**Comment by cedrick-f** [comment]
Bonjour
Merci, j'ai pu régler le problème.
