### ISSUE TITLE
Ouverture fichier 8.4-beta16

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#81]
Bonjour,
Pour ouvrir la première fois un fichier .seq à partir de l'explorateur windows en cliquant dessus, le fichier s'ouvre. Par contre une fois pysequence ouvert en cliquant sur un fichier .seq de l'explorateur le fichier ne s'ouvre pas il faut forcément passé par les menus de pysequence pour ouvrir ce deuxième fichier.
Bien cordialement

**Comment by cedrick-f** [comment]
Bonjour
Merci, c'est corrigé.
