### ISSUE TITLE
placement aléatoire des séquences dans une progression 8.4-beta16

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#83]
Bonjour,
Lors de l'importation de séquences dans une progression les séquences ne se mettent pas dans l'arborescence l'une à la suite de l'autre mais elles se placent de manière aléatoire.

![image](https://user-images.githubusercontent.com/11646494/82608710-7574cd00-9bbb-11ea-9ccc-5db4d17b2095.png)

> FILE_ENCODING utf-8
SYSTEM_ENCODING utf-8
pySequence installé dans C:\Program Files (x86)\pySequence\bin
pySequence démarré dans C:\Program Files (x86)\pySequence\bin
Dossier COMMUN pour les données : C:\ProgramData\pySequence
Dossier USER pour les données : C:\Users\a\AppData\Roaming\pySequence
sys.version_info(major=3, minor=6, micro=8, releaselevel='final', serial=0)
Locale : 79 (FR: 79 ;EN: 57 )
8.4-beta.16
Référentiels modifiés : []
Version Adobe Reader None
pdfviewer using PyMuPDF (GPL)
.xlsx
Options defaut
Ouverture Options: C:\Users\a\AppData\Roaming\pySequence\sequence.cfg
ouvrir D:\MECA\00_progression\pysequence\si\s1_01.prg False D:\MECA\00_progression\pysequence\si
Ouverture progression D:\MECA\00_progression\pysequence\si\s1_01.prg
Différence
   labels
  xml: {'SEQINT': ['Intitulé de la Séquence', 'Intitulé de la Séquence pédagogique', <widgets.Grammaire object at 0x06791A30>], 'ELEVES': ['Élève(s)$m', 'Élèves', <widgets.Grammaire object at 0x06744790>], 'OBJEC': ['Objectif(s) de formation$m', 'Objectifs de formation', <widgets.Grammaire object at 0x0622EC70>], 'PRJVAL': ['Fiche(s) de validation de projet$f', 'Fiche de validation de projet', <widgets.Grammaire object at 0x0622E6D0>], 'EXIG': ['Fonction(s) de service$f', 'Fonctions de service', <widgets.Grammaire object at 0x061687D0>]}
  xls: {'SEQINT': ['Intitulé de la Séquence', 'Intitulé de la Séquence pédagogique', <widgets.Grammaire object at 0x063D8F70>], 'ELEVES': ['Élève(s)$m', 'Élèves', <widgets.Grammaire object at 0x063D2FF0>], 'OBJEC': ['Objectif(s) de formation$m', 'Objectifs de formation', <widgets.Grammaire object at 0x063D2FB0>]}
Recherche nouvelle version ...
  proxies : {}
   locale  : 8.4-beta.16
   serveur : 8.3.5
   serveur_beta : 8.4-beta.16
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\Cedrick\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
  File "wx_pysequence.py", line 461, in run
TypeError: a bytes-like object is required, not 'str'
ouvrir D:\MECA\00_progression\pysequence\si\s1_06_5sem_01.seq False D:\MECA\00_progression\pysequence\si
ouvrir sequence D:\MECA\00_progression\pysequence\si\s1_06_5sem_01.seq
Différence
   labels
  xml: {'SEQINT': ['Intitulé de la Séquence', 'Intitulé de la Séquence pédagogique', <widgets.Grammaire object at 0x0D736C50>], 'ELEVES': ['Élève(s)$m', 'Élèves', <widgets.Grammaire object at 0x0D736B90>], 'OBJEC': ['Objectif(s) de formation$m', 'Objectifs de formation', <widgets.Grammaire object at 0x0D7360B0>], 'PRJVAL': ['Fiche(s) de validation de projet$f', 'Fiche de validation de projet', <widgets.Grammaire object at 0x0D736B70>], 'EXIG': ['Fonction(s) de service$f', 'Fonctions de service', <widgets.Grammaire object at 0x0D736A30>]}
  xls: {'SEQINT': ['Intitulé de la Séquence', 'Intitulé de la Séquence pédagogique', <widgets.Grammaire object at 0x063D8F70>], 'ELEVES': ['Élève(s)$m', 'Élèves', <widgets.Grammaire object at 0x063D2FF0>], 'OBJEC': ['Objectif(s) de formation$m', 'Objectifs de formation', <widgets.Grammaire object at 0x063D2FB0>]}

Bien cordialement
[si.zip](https://github.com/cedrick-f/pySequence/files/4664929/si.zip)

**Comment by michelwend** [comment]
Nouvel essai j'avais presque réussi. Mais sur la dernière importation dans la progression la séqy=unece se place en 2eme j'arrive a la changer de place une fois seulement, reste la dernière
[si2.zip](https://github.com/cedrick-f/pySequence/files/4668860/si2.zip)
 séquence à importer.

**Comment by cedrick-f** [comment]
Je n'ai rien relevé d'anormal chez moi.
Les séquences se placent bien dans leur période. Ensuite on ne peut les déplacer (par glisser/déposer) qu'à l’intérieur de cette même période.
Pour les changer de période, il faut le faire depuis leurs propriétés.
En revanche il y a bien en problème quand la position de la séquence est sur plusieurs périodes ... je cherche une solution ...

**Comment by michelwend** [comment]
Ok je regarde ce problème de période, merci.

**Comment by michelwend** [comment]
Je viens d'essayer de changer la période d'une séquence en ayant l'ensemble des séquences ouvertes et la progression. J'btiens l'erreur suivante:
`Traceback (most recent call last):
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\objects_wx.py", line 14120, in OnSelChanged
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\pysequence.py", line 2251, in GetPanelPropriete
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\objects_wx.py", line 5821, in __init__
  File "C:\Users\Cedrick\Documents\Developp\pysequence\src\objects_wx.py", line 5887, in MiseAJour
TypeError: 'tuple' object does not support item assignment`

**Comment by cedrick-f** [comment]
Normalement, cette erreur ne se produit plus dans la beta17

**Comment by michelwend** [comment]
Beta 17
Je suis entrain de refaire l'essai. Sur le fichier actuel de la progression impossible de déplacer les séquences existantes. Par conséquent je les efface toutes et les remets c'est très long..
![image](https://user-images.githubusercontent.com/11646494/82751275-6dcd4800-9db6-11ea-9de1-93df1490e8f8.png)
Je commence une nouvelle issue pour la suite sur la beta 17.
