### ISSUE TITLE
2snt pysequence 8.4-16

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#84]
Bonjour,
Pour les 2snt je n'arrive pas a sélectionner la période car les curseurs bougent difficilement. Passage direct du premier au deuxième trimestre...
![image](https://user-images.githubusercontent.com/11646494/82658114-c1a92700-9c26-11ea-8986-167f19a379e0.png)

![image](https://user-images.githubusercontent.com/11646494/82658459-4c8a2180-9c27-11ea-9d83-dc1bcfa0ec66.png)

Bien cordialement

**Comment by cedrick-f** [comment]
Bonjour
Bug corrigé, merci.
