### ISSUE TITLE
2snt progression import séquence 8.4-16

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#86]
[cit-si_snt.zip](https://github.com/cedrick-f/pySequence/files/4667935/cit-si_snt.zip)
Bonjour,
L'import d'une séquence dans une progression fonctionne un peu aléatoirement. Ici j'ai réussi l'importation jusqu'à la séquence 4. Ensuite les nouvelles importations fonctionnent mais elles se placent en 2eme position mais on peut les déplacer à la main pour les mettre au bon endroit. Cela fonctionne un temps. Pour la suite il faut sortir du programme puis redémarrer.

![image](https://user-images.githubusercontent.com/11646494/82666776-e0171e80-9c36-11ea-93fa-3c6c91beede3.png)

Merci encore et à bientôt

**Comment by cedrick-f** [comment]
Je ne constate aucun problème sur 8.4-beta.18.
Sans doute corrigé, à vérifier ...
