### ISSUE TITLE
déplacement onglet 8.4-16

### ISSUE THREAD

**Issue by michelwend** [cedrick-f/pySequence#88]
Bonjour,
Je ne sais plus si cela fonctionnait sur une version antérieure. Mais serait-il possible de pouvoir déplacer et ordonner les onglets des fichiers ouverts.
![image](https://user-images.githubusercontent.com/11646494/82727830-2dee5e00-9ced-11ea-84fe-93bddac9276e.png)
mw

**Comment by cedrick-f** [comment]
Bonjour
Ça marche parfaitement chez moi ...
Que se passe-t-il quand vous tentez un glissement ?

**Comment by michelwend** [comment]
Bonsoir,
Ce soir cela fonctionne..?
