### ISSUE TITLE
Évolution pour projet pluri spécialité en sti2d

### ISSUE THREAD

**Issue by jcfricou** [cedrick-f/pySequence#9]
Bonjour Cedrick,

Comme nous en avons discuté, de plus en plus de projets STI2D sont pluri spécialité mais il s'avère que parfois il n'y a que le nom du support qui est pluri mais le cahier des charges et le travail des eleves ne l'est pas. 
Pour éviter ceci les enseignants inscrivent dans une fiche d'une specialite, les élèves de ou des autres spécialités. Par exemple pour un projet Itec où il y a trois élèves associés à trois élèves EE, sur la fiche ITEC il y a aura 
Eleve ITEC 1
Élève ITEC 2
Eleve ITEC 3
Eleve EE 

Sur la fiche EE
Eleve EE 1
Élève EE 2
Eleve EE 3
Eleve ITEC

Cela permet d'avoir une définition et une répartition des tâches eleves cohérentes pour un projet pluri spécialité. Seulement dans l'exemple donné, les deux fiches de validation comptent quatre eleves alors que pour chaque specialite il n'y en a que trois.

Voici le problème posé, j'ai imaginé une solution qui me semble simple mais à toi de me dire. Lorsque l'on rajoute un eleve, il faudrait avoir la possibilité de préciser s'il est associé à la spécialité de la fiche en question ou non. Ensuite revoir le calcul du nombre d'élèves en prenant en compte seulement les eleves associés à la fiche pour la fiche de validation.

Je sais pas si j'ai été assez clair. N'hésite pas à m'appeler si besoin.
A+
Jc

**Comment by cedrick-f** [comment]
Salut JC

J'ai ajouté une fonctionnalité de groupe ... dis moi si ça colle avec ce 
que tu attendais.

A+

CF

**Comment by SebCanet** [comment]
Bonjour,
je ne sais pas si c'est le bon endroit pour rebondir, mais je ne parviens pas à intégrer les élèves DANS le groupe, j'ai l'impression que le groupe est de même niveau qu'un élève. Hors je voyais le groupe comme dans Linux.

Merci pour tout ce travail.

**Comment by cedrick-f** [comment]
Bonjour
La notion de Groupe dans pySéquence n'est pas là pour intégrer des élèves au projet, mais plutôt pour désigner un autre groupe d'élèves, travaillant sur une autre "branche" du même projet, et qui fait elle-même l'objet d'une autre fiche pySéquence.
Cette fonctionnalité est particulièrement utile en STI2D, où sur un même projet, on peut faire travailler des élèves de spécialité ITEC, SIN, ... Voir le premier message de ce fil.
En espérant avoir été assez clair.
Cédrick

**Comment by SebCanet** [comment]
Justement je fais SIN & ITEC en STI2D, donc j'essaie au maximum de faire ce genre de projets.
Mais ce serait intéressant que le groupe contienne le nom des élèves.

**Comment by cedrick-f** [comment]
Je vais voir ce que je peux faire ...

**Comment by cedrick-f** [comment]
Bonjour
Dans la future version 7.1.beta-9, on pourra ajouter une liste d'élèves aux groupes.
J'espère que ça répondra à tes attentes ...
