### ISSUE TITLE
Commit / fork

### ISSUE THREAD

**Issue by Bo-Ka** [cedrick-f/pySequence#97]
Bonjour,

Je souhaiterais contribuer à votre projet.
Par contre il m'est impossible de réaliser un commit.
Je ne peux pas non plus ouvrir le fork de pySequence que j'ai créé depuis GitHub.
Auriez-vous bloqué ces fonctionnalités ?

Bonne journée

**Comment by cedrick-f** [comment]
Bonjour
Je n'ai bloqué aucune fonctionnalité. D'autres utilisateurs ont pu créer un fork, mais le votre renvoie une belle erreur 500
Je pense que l'opération s'est mal passée.
A voir si en recommençant ça se reproduit...

Cédrick

**Comment by Bo-Ka** [comment]
Bonjour Cedrick,

Merci pour ta réactivité. 

En effet, impossible d'accéder au fork, par conséquent je ne peux le supprimer pour un recréer un autre.
J'attends des nouvelles du support de GitHub à ce sujet.

En attendant, j'ai importé ton dépôt sous un autre nom pour pouvoir y travailler. Par contre il n'est pas considéré comme un fork sous GitHub.

Merci encore
